services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - default
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - default
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  k6:
    image: grafana/k6:latest
    container_name: k6
    networks:
      - default
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/db0
    volumes:
      - ./tests:/tests
      - ./grafana:/grafana
      - ./utils:/utils
    depends_on:
      - influxdb
      
networks:
  default:

volumes:
  influxdb-storage:
  grafana-storage: